# Generated by Django 5.1.1 on 2024-11-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectchangeaddress',
            options={'verbose_name': 'Detect Change Address', 'verbose_name_plural': 'Detect Change Addresses'},
        ),
        migrations.AlterModelOptions(
            name='historicaldetectchangeaddress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Detect Change Address', 'verbose_name_plural': 'historical Detect Change Addresses'},
        ),
        migrations.AddField(
            model_name='historicalticketchangedate',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalticketchangedate',
            name='action_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalticketchangedate',
            name='apply_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticketchangedate',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticketchangedate',
            name='order_status',
            field=models.CharField(blank=True, choices=[('En-route to Sorting Hub', 'En-route to Sorting Hub'), ('Arrived at Sorting Hub', 'Arrived at Sorting Hub'), ('Pending Reschedule', 'Pending Reschedule'), ('Pending Pickup', 'Pending Pickup'), ('Pending Pickup at Distribution Point', 'Pending Pickup at Distribution Point'), ('On Vehicle for Delivery', 'On Vehicle for Delivery'), ('On Hold', 'On Hold'), ('Transferred to 3PL', 'Transferred to 3PL'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalticketchangedate',
            name='rts_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketchangedate',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketchangedate',
            name='action_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketchangedate',
            name='apply_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchangedate',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketchangedate',
            name='order_status',
            field=models.CharField(blank=True, choices=[('En-route to Sorting Hub', 'En-route to Sorting Hub'), ('Arrived at Sorting Hub', 'Arrived at Sorting Hub'), ('Pending Reschedule', 'Pending Reschedule'), ('Pending Pickup', 'Pending Pickup'), ('Pending Pickup at Distribution Point', 'Pending Pickup at Distribution Point'), ('On Vehicle for Delivery', 'On Vehicle for Delivery'), ('On Hold', 'On Hold'), ('Transferred to 3PL', 'Transferred to 3PL'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticketchangedate',
            name='rts_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalticketchangeaddress',
            name='order_status',
            field=models.CharField(blank=True, choices=[('En-route to Sorting Hub', 'En-route to Sorting Hub'), ('Arrived at Sorting Hub', 'Arrived at Sorting Hub'), ('Pending Reschedule', 'Pending Reschedule'), ('Pending Pickup', 'Pending Pickup'), ('Pending Pickup at Distribution Point', 'Pending Pickup at Distribution Point'), ('On Vehicle for Delivery', 'On Vehicle for Delivery'), ('On Hold', 'On Hold'), ('Transferred to 3PL', 'Transferred to 3PL'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketchangeaddress',
            name='order_status',
            field=models.CharField(blank=True, choices=[('En-route to Sorting Hub', 'En-route to Sorting Hub'), ('Arrived at Sorting Hub', 'Arrived at Sorting Hub'), ('Pending Reschedule', 'Pending Reschedule'), ('Pending Pickup', 'Pending Pickup'), ('Pending Pickup at Distribution Point', 'Pending Pickup at Distribution Point'), ('On Vehicle for Delivery', 'On Vehicle for Delivery'), ('On Hold', 'On Hold'), ('Transferred to 3PL', 'Transferred to 3PL'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], max_length=255, null=True),
        ),
    ]
