# Generated by Django 5.1.1 on 2024-10-28 11:11

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServiceAccount',
            fields=[
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('type', models.CharField(default='service_account', max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('private_key_id', models.CharField(db_index=True, max_length=255)),
                ('_private_key', models.TextField(db_column='private_key')),
                ('client_email', models.EmailField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('auth_uri', models.URLField(default='https://accounts.google.com/o/oauth2/auth', max_length=255)),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('auth_provider_x509_cert_url', models.URLField(default='https://www.googleapis.com/oauth2/v1/certs', max_length=255)),
                ('universe_domain', models.CharField(default='googleapis.com', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Google Service Account',
                'verbose_name_plural': 'historical Google Service Accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('type', models.CharField(default='service_account', max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('project_id', models.CharField(max_length=255)),
                ('private_key_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('_private_key', models.TextField(db_column='private_key')),
                ('client_email', models.EmailField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('auth_uri', models.URLField(default='https://accounts.google.com/o/oauth2/auth', max_length=255)),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('auth_provider_x509_cert_url', models.URLField(default='https://www.googleapis.com/oauth2/v1/certs', max_length=255)),
                ('universe_domain', models.CharField(default='googleapis.com', max_length=255)),
            ],
            options={
                'verbose_name': 'Google Service Account',
                'verbose_name_plural': 'Google Service Accounts',
                'ordering': ('project_id', 'client_email'),
            },
        ),
    ]
