# Generated by Django 5.1.1 on 2024-10-30 03:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('job_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('query_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Success'), (4, 'Failure'), (5, 'Cancelled')], default=1)),
                ('error', models.TextField(blank=True, null=True)),
                ('result_id', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalJob',
            fields=[
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('job_id', models.CharField(db_index=True, max_length=36)),
                ('query_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Success'), (4, 'Failure'), (5, 'Cancelled')], default=1)),
                ('error', models.TextField(blank=True, null=True)),
                ('result_id', models.BigIntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical job',
                'verbose_name_plural': 'historical jobs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
