# Generated by Django 5.1.1 on 2024-11-14 08:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pre Success Driver',
                'verbose_name_plural': 'Pre Success Drivers',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('driver_id', models.IntegerField(blank=True, db_index=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pre Success Driver',
                'verbose_name_plural': 'historical Pre Success Drivers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRoute',
            fields=[
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('route_id', models.IntegerField(blank=True, db_index=True)),
                ('archived', models.BooleanField(default=False)),
                ('shipper_group', models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('Unknown', 'Unknown')], max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pre_success.driver')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pre Success Route',
                'verbose_name_plural': 'historical Pre Success Routes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('archived', models.BooleanField(default=False)),
                ('shipper_group', models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('Unknown', 'Unknown')], max_length=255, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='pre_success.driver')),
            ],
            options={
                'verbose_name': 'Pre Success Route',
                'verbose_name_plural': 'Pre Success Routes',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('tracking_id', models.CharField(max_length=255)),
                ('order_id', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=255, null=True)),
                ('granular_status', models.CharField(choices=[('En-route to Sorting Hub', 'En-route to Sorting Hub'), ('Arrived at Sorting Hub', 'Arrived at Sorting Hub'), ('Pending Reschedule', 'Pending Reschedule'), ('Pending Pickup', 'Pending Pickup'), ('Pending Pickup at Distribution Point', 'Pending Pickup at Distribution Point'), ('On Vehicle for Delivery', 'On Vehicle for Delivery'), ('On Hold', 'On Hold'), ('Transferred to 3PL', 'Transferred to 3PL'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], max_length=255, null=True)),
                ('rts', models.BooleanField(default=False)),
                ('waypoint_id', models.BigIntegerField(blank=True, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('project_call', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_id', models.BigIntegerField(blank=True, null=True)),
                ('investigating_hub_id', models.IntegerField(blank=True, null=True)),
                ('last_instruction', models.TextField(blank=True, null=True)),
                ('dest_hub_id', models.IntegerField(null=True)),
                ('parcel_sweeper', models.BooleanField(default=False)),
                ('shipper_group', models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('Unknown', 'Unknown')], max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pre_success.route')),
            ],
            options={
                'verbose_name': 'historical Pre Success Order',
                'verbose_name_plural': 'historical Pre Success Orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(null=True)),
                ('tracking_id', models.CharField(max_length=255)),
                ('order_id', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=255, null=True)),
                ('granular_status', models.CharField(choices=[('En-route to Sorting Hub', 'En-route to Sorting Hub'), ('Arrived at Sorting Hub', 'Arrived at Sorting Hub'), ('Pending Reschedule', 'Pending Reschedule'), ('Pending Pickup', 'Pending Pickup'), ('Pending Pickup at Distribution Point', 'Pending Pickup at Distribution Point'), ('On Vehicle for Delivery', 'On Vehicle for Delivery'), ('On Hold', 'On Hold'), ('Transferred to 3PL', 'Transferred to 3PL'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned to Sender', 'Returned to Sender')], max_length=255, null=True)),
                ('rts', models.BooleanField(default=False)),
                ('waypoint_id', models.BigIntegerField(blank=True, null=True)),
                ('time_stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('project_call', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_id', models.BigIntegerField(blank=True, null=True)),
                ('investigating_hub_id', models.IntegerField(blank=True, null=True)),
                ('last_instruction', models.TextField(blank=True, null=True)),
                ('dest_hub_id', models.IntegerField(null=True)),
                ('parcel_sweeper', models.BooleanField(default=False)),
                ('shipper_group', models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('Unknown', 'Unknown')], max_length=255, null=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pre_success.route')),
            ],
            options={
                'verbose_name': 'Pre Success Order',
                'verbose_name_plural': 'Pre Success Orders',
                'constraints': [models.UniqueConstraint(fields=('tracking_id', 'project_call'), name='unique_tracking_project')],
            },
        ),
    ]
