# Generated by Django 5.1.1 on 2024-11-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_success', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='shipper_group',
            field=models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('TTDI', 'Ttid'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='shipper_group',
            field=models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('TTDI', 'Ttid'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper_group',
            field=models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('TTDI', 'Ttid'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='shipper_group',
            field=models.CharField(blank=True, choices=[('TikTok Domestic', 'Tiktok'), ('Shopee', 'Shopee'), ('TTDI', 'Ttid'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
