name: Create Migrations and Release

on:
  push:
    branches:
      - migrations

jobs:
  create_migrations:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install required packages for mysqlclient
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          pkg-config \
          python3-dev \
          default-libmysqlclient-dev \
          build-essential \
          && sudo apt-get clean \
          && sudo rm -rf /var/lib/apt/lists/*

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Set up environment variables
      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      # Step 6: Run makemigrations
      - name: Run makemigrations
        run: |
          python manage.py makemigrations

      # Step 7: Commit and push migrations, bypassing .gitignore
      - name: Commit and push migrations if any changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          # List and force-add ignored migration files
          MIGRATION_FILES=$(git ls-files --others -i --exclude-standard */migrations/*.py)
          if [ -n "$MIGRATION_FILES" ]; then
            echo "$MIGRATION_FILES" | xargs git add -f
            git commit -m "Auto-generate migrations"
            git push "https://${GITHUB_TOKEN}@github.com/kietdev-ninjavan/STOsPlatform.git" HEAD:migrations
          else
            echo "No changes in migrations to commit"
          fi
