name: Create Migrations and Release

on:
  push:
    branches:
      - migrations

jobs:
  create_migrations:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install required packages for mysqlclient
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          pkg-config \
          python3-dev \
          default-libmysqlclient-dev \
          build-essential \
          && sudo apt-get clean \
          && sudo rm -rf /var/lib/apt/lists/*

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Set up environment variables
      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      # Step 6: Run makemigrations
      - name: Run makemigrations
        run: |
          python manage.py makemigrations

      # Step 7: Commit and push migrations, bypassing .gitignore
      - name: Commit and push migrations if any changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          # Check if there are any untracked or modified files in the migrations folder
          if [ -n "$(git status --porcelain */migrations/*.py)" ]; then
            git add -f */migrations/*.py # Force add all migration files
            git commit -m "Auto-generate migrations"
            git push origin migrations
          else
            echo "No changes in migrations to commit"
          fi
      
