name: Release Docker Image

on:
  release:
    types: [published]  # This triggers the workflow when a release is published.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform builds if necessary)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Extract the release version from the GitHub release tag
      - name: Extract version from the tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 5: Build and tag Docker image with the release version and 'latest'
      - name: Build and tag Docker image
        run: |
          docker build -t kietnjv/stosplatform:${{ env.VERSION }} .
          docker tag kietnjv/stosplatform:${{ env.VERSION }} kietnjv/stosplatform:latest

      # Step 6: Push the Docker image to your Docker Hub repository
      - name: Push Docker image to Docker Hub
        run: |
          docker push kietnjv/stosplatform:${{ env.VERSION }}
          docker push kietnjv/stosplatform:latest
