# Generated by Django 5.1.1 on 2024-11-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla_tool', '0004_historicaltiktokbacklog_backlog_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshopeebacklog',
            name='zns_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopeebacklog',
            name='zns_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
